# Generated by Django 3.1.2 on 2020-10-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zircon_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
